### ISSUE TITLE
Set max for font size for large displays

### ISSUE THREAD

**Issue by timklapdor** [timklapdor/learning-materials#11]
Look at CSULX site - should be able to reuse code - also <https://madebymike.com.au/writing/precise-control-responsive-typography/>

**Comment by timklapdor** [comment]
Added new responsive type calc:
```css
@media screen and (min-width: 300px) {
  #containerdiv .vtbegenerated, .staffInfoList .details  {font-size: calc( 16px + (24 - 16) * ( (100vw - 300px) / ( 1400 - 300) )) !important;}
  .vtbegenerated div.content, .vtbegenerated div.breakout  {width: 100% !important;}
}

@media screen and (min-width: 1400px) {
  #containerdiv .vtbegenerated, .staffInfoList .details  {font-size: 24px !important; }
}
```

and added another media query for 2400px displays:

```css
#containerdiv .vtbegenerated, .staffInfoList .details  {font-size: 30px !important; }
```
