### ISSUE TITLE
Style Mybb Flyout

### ISSUE THREAD

**Issue by timklapdor** [timklapdor/learning-materials#38]
at per https://community.blackboard.com/people/emunoz/blog/2017/02/21/my-blackboard-flyout 

```css
.flyout-menu {background-color: #121214; -moz-border-radius: 0 0 4px 4px; -webkit-border-radius: 0 0 4px 4px; border-radius: 0 0 4px 4px; border-color: rgba(0, 0, 0, 0.1) rgba(0, 0, 0, 0.1) rgba(0, 0, 0, 0.25);} /*This is the sidebar, all the way*/
.flyout-menu .mybb-tools {background-color: #121214 !important;} /*This is the sidebar, only the part with icons*/
.flyout-menu a {color: #0088CC !important;} /*links*/
.flyout-menu a:hover {color: #0099E6 !important;}
.flyout-menu .accordion_toggle span {background-color: #FFFFFF;color: #333333 !important;} /*titles*/
.flyout-menu .accordion_toggle:hover span {background-color: #FFFFFF;color: #333333 !important;}
.accordion_content {background-color: #FFFFFF!important; -moz-box-shadow: none !important; -webkit-box-shadow: none !important; box-shadow: none!important;} /*content*/
.accordion_content li a {color: #0088CC; font-size: 100%; text-decoration: none;}
.bottom-buttons a:hover, .bottom-buttons a:focus  {background-color: #0088CC !important;} /*buttons to help and institution*/
```
