### ISSUE TITLE
Missing Home Icon

### ISSUE THREAD

**Issue by timklapdor** [timklapdor/learning-materials#7]
Missing home icon in sites. Can use pre-existing CSS to hide subject code and name and replace with Home Icon.

**Comment by timklapdor** [comment]
Replaced using CSS

**Comment by timklapdor** [comment]
Fixed with css:

```css
.coursePath .courseId, .coursePath .courseName {display: none;}

.coursePath > a:before {
content: 'H';
font-family: 'Utilicons';
font-size: 20px
}
```
