### ISSUE TITLE
Spacing in Table's for activities

### ISSUE THREAD

**Issue by timklapdor** [timklapdor/learning-materials#8]
When multiple tables are stacked on top of each other they are spaced too much. 

Need to add ```TABLE + TABLE``` rule to change ```margin``` or  ``` padding```

**Comment by timklapdor** [comment]
fixing with 

``` css
#containerdiv .vtbegenerated br + table, #containerdiv .vtbegenerated table + table {
margin-top: -1em !important;
}
```
